[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"
  
[[redirects]]
  from = "/api/*"
  to = "https://mern-chatapp-backend-295e.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/socket.io/*"
  to = "https://mern-chatapp-backend-295e.onrender.com/socket.io/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
